require: rubocop-rails

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/LambdaCall:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Exclude:
    - "config/rubber/**/*"

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - config/routes.rb
    - config/environments/**/*
    - lib/tasks/**/*

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 160

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - "Gemfile.lock"
    - "bin/**/*"
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"
    - "db/schema.rb"
    - "config/initializers/**/*"
